finishes = ["Black Metal",
            "White Metal",
            "Brushed Metal",
            "Golden Metal",
            "Black Plastic",
            "White Plastic",
            "Gray Plastic",
            "Green Plastic",
            "Yellow Plastic",
            "Black Paint",
            "White Paint",
            "Gray Paint",
            "Green Paint",
            "Yellow Paint"]

models = {"FLOS": [{"name": "C1",
                    "productCode": "03.1235.DR",
                    "lm": 1225,
                    "w": 14,
                    "fixtureType": "Spot",
                    "length": 0,
                    "width": 0,
                    "height": 0,
                    "diameter": 0,
                    "temperature": 3000,
                    "usage": "General",
                    "price": 400,
                    "finish": "Black Metal"
                   },

                   {"name": "Super Line & Pro",
                    "productCode": "03.9503.14",
                    "lm": 4794,
                    "w": 58,
                    "fixtureType": "Linear",
                    "length": 1500,
                    "width": 45,
                    "height": 25,
                    "diameter": 0,
                    "temperature": 4000,
                    "usage": "General",
                    "price": 800,
                    "finish": "Black Metal"
                   },
                   
                   {"name": "Light Bell",
                    "productCode": "03.1235.DR",
                    "lm": 6714,
                    "w": 55,
                    "fixtureType": "Circular",
                    "length": 0,
                    "width": 0,
                    "height": 0,
                    "diameter": 228,
                    "temperature": 3000,
                    "usage": "General",
                    "price": 900,
                    "finish": "Black Metal"
                   },

                   {"name": "Super Flat",
                    "productCode": "09.5011.02B",
                    "lm": 7660,
                    "w": 50,
                    "fixtureType": "Rectangular",
                    "length": 1200,
                    "width": 300,
                    "height": 14,
                    "diameter": 0,
                    "temperature": 4000,
                    "usage": "General",
                    "price": 700,
                    "finish": "Brushed Metal"
                   },

                   {"name": "Light Shadow Surface",
                    "productCode": "03.8829.40A",
                    "lm": 1080,
                    "w": 10,
                    "fixtureType": "Spot",
                    "length": 147,
                    "width": 42,
                    "height": 25,
                    "diameter": 0,
                    "temperature": 2700,
                    "usage": "General",
                    "price": 700,
                    "finish": "Black Metal"
                   },
                  ],

            "Vibia": [{"name": "Alpha",
                       "productCode": "7940",
                       "lm": 139,
                       "w": 2,
                       "fixtureType": "Spot",
                       "length": 127,
                       "width": 127,
                       "height": 25,
                       "diameter": 0,
                       "temperature": 2700,
                       "usage": "Bedroom",
                       "price": 200,
                       "finish": "Brushed Metal"
                    },

                    {"name": "Big",
                     "productCode": "0537",
                     "lm": 5638,
                     "w": 76,
                     "fixtureType": "Circular",
                     "length": 0,
                     "width": 0,
                     "height": 0,
                     "diameter": 1200,
                     "temperature": 3500,
                     "usage": "General",
                     "price": 800,
                     "finish": "White Metal"
                    },
                    
                    {"name": "Domo",
                     "productCode": "8200",
                     "lm": 350,
                     "w": 6,
                     "fixtureType": "Spot",
                     "length": 0,
                     "width": 0,
                     "height": 0,
                     "diameter": 0,
                     "temperature": 2700,
                     "usage": "General",
                     "price": 300,
                     "finish": "Black Metal"
                    },

                    {"name": "Duo",
                     "productCode": "4870",
                     "lm": 1666,
                     "w": 26,
                     "fixtureType": "Circular",
                     "length": 0,
                     "width": 0,
                     "height": 127,
                     "diameter": 457,
                     "temperature": 2700,
                     "usage": "General",
                     "price": 700,
                     "finish": "Brushed Metal"
                    },

                    {"name": "Flat",
                     "productCode": "5935",
                     "lm": 138,
                     "w": 20,
                     "fixtureType": "Circular",
                     "length": 0,
                     "width": 0,
                     "height": 0,
                     "diameter": 400,
                     "temperature": 2700,
                     "usage": "General",
                     "price": 1200,
                     "finish": "Brushed Metal"
                    },
                  ],

            "Passun Lighting": [{"name": "LPL217",
                                 "productCode": "LPL217",
                                 "lm": 430,
                                 "w": 5,
                                 "fixtureType": "Circular",
                                 "length": 0,
                                 "width": 0,
                                 "height": 100,
                                 "diameter": 205,
                                 "temperature": 3000,
                                 "usage": "General",
                                 "price": 200,
                                 "finish": "Black Paint"
                                },

                                {"name": "LPL256",
                                 "productCode": "LPL256",
                                 "lm": 10800,
                                 "w": 108,
                                 "fixtureType": "Circular",
                                 "length": 0,
                                 "width": 0,
                                 "height": 0,
                                 "diameter": 922,
                                 "temperature": 3000,
                                 "usage": "General",
                                 "price": 800,
                                 "finish": "Golden Metal"
                                },
                                
                                {"name": "LBL135",
                                 "productCode": "LBL135-BK",
                                 "lm": 430,
                                 "w": 5,
                                 "fixtureType": "Spot",
                                 "length": 0,
                                 "width": 0,
                                 "height": 0,
                                 "diameter": 0,
                                 "temperature": 3000,
                                 "usage": "General",
                                 "price": 150,
                                 "finish": "Black Metal"
                                },

                                {"name": "LBL203",
                                 "productCode": "LBL203-BK",
                                 "lm": 1200,
                                 "w": 12,
                                 "fixtureType": "Rectangular",
                                 "length": 174,
                                 "width": 174,
                                 "height": 37,
                                 "diameter": 0,
                                 "temperature": 2700,
                                 "usage": "General",
                                 "price": 200,
                                 "finish": "Black Metal"
                                },

                                 {"name": "LPL159",
                                 "productCode": "LPL159-SL",
                                 "lm": 1600,
                                 "w": 20,
                                 "fixtureType": "Linear",
                                 "length": 1200,
                                 "width": 50,
                                 "height": 70,
                                 "diameter": 0,
                                 "temperature": 3000,
                                 "usage": "Office",
                                 "price": 750,
                                 "finish": "Brushed Metal"
                                },
                            ],

            "ERCO": [{"name": "Jilly Linear",
                      "productCode": None,
                      "lm": 4490,
                      "w": 24,
                      "fixtureType": "Linear",
                      "length": 1500,
                      "width": 121,
                      "height": 25,
                      "diameter": 0,
                      "temperature": 3000,
                      "usage": "Office",
                      "price": 800,
                      "finish": "White Metal"
                    },

                    {"name": "Jilly Rectangular",
                     "productCode": None,
                     "lm": 6735,
                     "w": 36,
                     "fixtureType": "Rectangular",
                     "length": 152,
                     "width": 152,
                     "height": 62,
                     "diameter": 0,
                     "temperature": 2700,
                     "usage": "Office",
                     "price": 700,
                     "finish": "Brushed Metal"
                    },

                    {"name": "Quintessence",
                     "productCode": None,
                     "lm": 3300,
                     "w": 24,
                     "fixtureType": "Spot",
                     "length": 0,
                     "width": 0,
                     "height": 0,
                     "diameter": 0,
                     "temperature": 4000,
                     "usage": "Office",
                     "price": 800,
                     "finish": "White Metal"
                    },
                    
                    {"name": "Starpoint",
                     "productCode": None,
                     "lm": 830,
                     "w": 8,
                     "fixtureType": "Spot",
                     "length": 0,
                     "width": 0,
                     "height": 0,
                     "diameter": 0,
                     "temperature": 4000,
                     "usage": "Office",
                     "price": 1000,
                     "finish": "Brushed Metal"
                    },

                    {"name": "Compar Linear",
                     "productCode": None,
                     "lm": 9070,
                     "w": 78,
                     "fixtureType": "Linear",
                     "length": 1200,
                     "width": 38,
                     "height": 72,
                     "diameter": 0,
                     "temperature": 4000,
                     "usage": "Office",
                     "price": 700,
                     "finish": "White Metal"
                    },
                ],
         }

materialTypes = [
    "Metal",
    "Plastic",
    "Paint",
    "Glass",
    "Wood"
]

floorPlanShapes = [
  "Rectangular",
  "Circular",
  "Irregular",
  "Other"
]

# Material, albedo pairs
archMaterials ={"Paint, White" : 0.8,
  "Paint, Black" : 0.3,
  "Paint, Gray" : 0.5,
  "Paint, Blue" : 0.6,
  "Paint, Green" : 0.6,
  "Paint, Yellow" : 0.6,
  "Paint, Red" : 0.5,
  "Brick, Common" : 0.6,
  "Concrete" : 0.5,
  "Concrete, Polished" : 0.6,
  "Wood" : 0.5,
  "Ceramic, White" : 0.8,
  "Ceramic, Gray" : 0.6,
  "Ceramic, Slate" : 0.5,
  "Ceramic, Beige" : 0.6,
}